name: Build and Release Plugin

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build plugin
        run: yarn build

      - name: Create release folder and zip
        run: |
          mkdir release
          cp -r dist/* release/
          cp package.json README.md LICENSE logseq.png release/
          cd release && zip -r ../logseq-composer.zip .

      - name: Upload plugin zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: logseq-composer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
